nager.date.api.base-url=https://date.nager.at/api/v3

# Server configuration
server.port=8080

# Logging
logging.level.com.acn.holidayapi=DEBUG
logging.level.org.springframework.web=INFO
logging.level.reactor.netty=INFO
logging.level.org.springframework.web.servlet.resource=WARN

# SSL Truststore configuration (used by WebClientConfig)
ssl.truststore.path=certs/truststore.jks

server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always


spring.web.resources.add-mappings=false
logging.level.org.springframework.web.servlet.resource=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation=INFO

# Cache configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h


